services:
  rabbitmq:
    image: rabbitmq:4.0.4-management-alpine
    hostname: rabbitmq
    restart: always
    volumes:
      - ./rabbit-data:/var/lib/rabbitmq
    ports:
        - 15672:15672
        - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
