services:
  rabbitmq:
    image: rabbitmq:4.0.4-management-alpine
    ports:
        - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
